config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login'
  post '/login', to: 'users#logincreate'
  delete '/logout', to: 'users#logout'
  get '/transactions/no-grp', to: 'transactions#no_grp'
  resources :users, only: %i[create show]
  resources :groups, only: %i[index show new create]
  resources :transactions, only: %i[index show new create]
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 4..30 },
                   uniqueness: true

  has_many :transactions
  belongs_to :user

  scope :in_u_g, -> { includes(:user, :group) }
  scope :dsc, -> { order('created_at DESC') }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, presence: true, length: { in: 4..30 },
                   uniqueness: true
  validates :description, presence: true, length: { in: 8..120 }
  validates :amount, presence: false, numericality: false
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :group, optional: true

  scope :in_u_g, -> { includes(:user, :group) }
  scope :dsc, -> { order('created_at DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.name = name.camelize }
  before_save { self.icon = Faker::Avatar.image }

  validates :name, presence: true, length: { in: 4..30 },
                   uniqueness: true

  has_many :groups
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper
  before_action :logged_in_user, only: %i[new create index show]

  def new
    @icons = icons
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      flash[:success] = "'#{@group.name}' group created successfully!"
      redirect_to @group
    else
      @icons = icons
      render 'new'
    end
  end

  def index
    @groups = Group.all.order('name')
  end

  def show
    @group = Group.find_by(id: params[:id])
    @transactions = Transaction.in_u_g.where(group_id: @group.id).dsc
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :logged_in_user, only: %i[new create show index]

  def new
    @transaction = Transaction.new
    @groups = Group.all.collect { |group| [group.name, group.id] }
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)
    if @transaction.save
      flash[:success] = "#{@transaction.name} transaction successfully created"
      redirect_to @transaction
    else
      render 'new'
    end
  end

  def show
    @transaction = Transaction.find_by(id: params[:id])
  end

  def index
    @transactions = Transaction.in_u_g.where(user_id: current_user.id).dsc
  end

  def no_grp
    @transactions = Transaction.in_u_g.where({ group_id: nil, user_id: current_user.id }).dsc
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name,
                                        :description,
                                        :amount,
                                        :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[show logout]
  before_action :already_in, only: %i[new login]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Account created successfully!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show; end

  # basic User Session methods
  def login; end

  def logincreate
    @user = User.find_by(name: params[:session][:name])
    if @user
      session[:user_id] = @user.id
      flash[:success] = "#{@user.name} you are logged in!"
      redirect_to @user
    else
      flash.now[:danger] = "User doesn't exist, please sign up"
      render 'login'
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    @user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please login or signup to have access'
    redirect_to root_path
  end

  def already_in
    redirect_to current_user if logged_in?
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # To get the links for the icon images.
  # Need: link(data-icon_src), name(data-name), author(data-author_name)
  # & site flaticon.com
  def icons
    html_data = RestClient.get('https://www.flaticon.com/packs/minimal-school')
    nok_obj = Nokogiri::HTML(html_data)
    tags = nok_obj.xpath('//html/body/section/div/div/section/ul/li')
    i_hash = {}
    tags.each_with_index do |li, i|
      i_hash[i] = {
        'name' => li['data-name'],
        'link' => li['data-icon_src'],
        'auth' => li['data-author_name']
      }
    end
    i_hash
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group.html.erb
 <%= link_to(group_url(group.id), class: "text-decoration-none") do %>
  <div class="box-hvr card mb-3 mx-3 d-flex flex-row p-3 justify-content-between">
    <img src="<%= group.icon %>" alt="" class="border border-warning rounded my-auto">
    <p class="text-decoration-none h4 m-0 align-self-center px-1  overflow-hidden">
      <%= group.name %>
    </p>
    <p class="date m-0 pr-sm-2 align-self-center text-center">
      <small class="text-muted"><%= group.created_at.strftime('%d %b %Y') %></small>
    </p>
  </div>
<% end %>

app/views/groups/index.html.erb
<% provide(:title, 'Groups') %>
<div>
  <%= render @groups %>
</div>

<%= link_to new_group_path, class: "link-btn btn
                  btn-success w-100 p-4 rounded-0" do %>
  <span class="p-3 border border-light">NEW GROUP</span>
<% end %>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>

<%= form_for @group, html: { class: "mt-5 mx-3" } do |f| %>

  <%= f.text_field :name, class: "form-control mb-3", placeholder: "Name" %>

  <ul class="icon-select btn-group flex-wrap p-0">
    <p class="grp-sel text-muted w-100 mt-1">Group</p>
      <li class="btn btn-light p-0 m-1">
        <%= f.radio_button :icon, @icons[25]['link'] %>
        <%= f.label :icon, value: @icons[25]['link'], class: "w-100 h-100 py-2" do %>
          <img src="<%= @icons[25]['link']%>" alt="">
        <% end %>
      </li>
    <% 1.upto(15) do |i| %>
      <li class="btn btn-light p-0 m-1">
        <%= f.radio_button :icon, @icons[i]['link'] %>
        <%= f.label :icon, value: @icons[i]['link'], class: "w-100 h-100 py-2" do %>
          <img src="<%= @icons[i]['link']%>" alt="">
        <% end %>
      </li>
    <% end %>
  </ul>

  <%= f.submit class: "btn btn-primary my-4 mx-auto d-block" %>

  <%= render  partial: 'shared/form_errors', locals: { model: @group } %>

<% end %>

app/views/groups/show.html.erb
<% provide(:title, 'Group Details') %>

<ul class="card mx-3 list-group list-group-flush p-3">
  <li class="list-group-item p-0 d-flex justify-content-between">
    <h4 class="mt-2 mb-4"><%= @group.name %></h4>
    <img src="<%= @group.icon %>" alt="" class="grp-img mb-2 border border-warning rounded">
  </li>

  <li class="list-group-item p-0 pt-3">
    <%= render @transactions %>
  </li>

  <%# <li class="list-group-item d-flex justify-content-between p-0 pt-3">
    <p class="m-0">TOTAL AMOUNT</p>
    <span class="font-weight-bold">$<%= number_with_precision(@transactions.sum(:amount), :precision => 2) %></span>
  <%# </li> %>
</ul>

  <% flash.each do |m_type, msg| %>
    <div class="alert alert-<%= m_type %> w-75 mx-auto text-center mt-3">
      <%= msg %>
    </div>
  <% end %>

<%= link_to new_group_path, class: "link-btn btn
                  btn-success w-100 p-4 rounded-0" do %>
  <span class="p-3 border border-light">NEW GROUP</span>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%# right-side burguer icon %>
  <% unless logged_in? %>
    <a href="/">
  <% else %>
    <a href="/users/<%= current_user.id %>" class="burguer">
    <%#= link_to current_user do %>
  <% end %>
    <button class="navbar-toggler">
      <span class="navbar-toggler-icon"></span>
    </button>
  </a>

  <h4 class="title nav-item text-light mb-0 mx-auto text-center"><%= yield(:title).upcase %></h4>

  <div class="nav-item"></div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Tracker</title>
      <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta name="title" property="og:title" content="Group our Transactions">
     <meta property="og:type" content="web-app">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <div class="container w-100" id="main_container">
      <%# to not show the navbar in the home page %>
      <% unless yield(:title) == 'Home' || yield(:title) == 'Profile' %>
        <%= render  "layouts/header" %>
      <% end %>

      <% unless controller_name == 'users' && action_name == 'show' %>
        <div class="pt-3 overflow-auto d-flex flex-column
                      justify-content-between" id="subcontainer">
      <% else %>
        <div class="container px-0 overflow-auto h-100" id="subcontainer">
      <% end %>

        <%= yield %>

        <% if action_name != 'show' %>
          <% flash.each do |m_type, msg| %>
            <div class="alert alert-<%= m_type %> w-75 mx-auto text-center mt-3">
              <%= msg %>
            </div>
          <% end %>
        <% end %>
      
      </div>
    </div>
  </body>
</html>

app/views/shared/_form.html.erb
<% if :title == 'Login' %>
  <%= form_with scope: :session, url: login_path do |f| %>
<% end %>

  <%= render  'shared/form_errors' %>

  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: "form-control" %>

  <% if @group %>
    <%= f.label :icon, "Icon" %>
    <%= f.text_field :icon %>
  <% elsif @transaction %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "" %>

    <%= f.label :amount %>
    <%# <%= f.number_field (:amount, in: ${0.0..20.0}, step: ${0.5}) %>

    <%= f.label :group_id %>
    <%# <%= f.number_field (:group_id, in: 1..Group.last.id, step: ${0.5}) %>

    <%= f.hidden_field :user_id, value: @user.id %>
  <% end %>

<% end %>

app/views/shared/_form_errors.html.erb
<% if model && model.errors.any? %>
  <p class="alert alert-danger text-muted w-75 mx-auto">
    The form contains <%= pluralize(model.errors.count, ' error') %>
  </p>
  <ul class="error_list mx-auto w-75 mx-auto">
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="home_title justify-content-center d-flex">
  <h1 class="align-self-center text-center">E-Tracket APP</h1>
</div>
<div class="home_buttons">
  <%= link_to  "Login", login_path, class: "btn btn-primary btn-lg btn-block" %>
  <%= link_to  "Signup", signup_path, class: "btn btn-success btn-lg btn-block" %>
</div>

app/views/transactions/_transaction.html.erb
<a href="<%= transaction_url(transaction.id) %>" class="text-decoration-none">
  <div class="box-hvr card mb-3 mx-3 d-flex flex-row">
    <div class="img-frame border border-warning rounded my-auto ml-2">
      <% if transaction.group %>
        <img src="<%= transaction.group.icon %>" alt="" class="">
      <% else %>
        <small class="text-muted d-block text-center mt-5 font-weight-bold">no group</small>
      <% end %>
    </div>
    <div class="right-content flex-grow-1">
      <div class="top-content d-flex p-3 justify-content-between">
        <h5 class="text-muted m-0"><%= transaction.name %></h5>
        <%# <p class="font-weight-bold m-0 text-dark">
          $<%= number_with_precision(transaction.amount, :precision => 2) %>
        <%# </p> %>
      </div>

      <div class="btm-content d-flex justify-content-between">
        <p class="ml-3">
          <small class="text-muted">
            <%= transaction.created_at.strftime('%d %b %Y') %>
          </small>
        </p>

        <% if controller_name == 'groups' && action_name == 'show' %>
          <p class="text-muted font-weight-bold mr-3"><%= transaction.user.name %>'s</p>
        <% end %>
      </div>
    </div>
  </div>
</a>

app/views/transactions/index.html.erb
<% provide(:title, 'Projects') %>


<div>
  <%# <div class="card mb-3 p-3 flex-row justify-content-between border-top-0" id="trn-total">
    <h5 class="text-muted m-0">Total Amount</h5>
    <p class="font-weight-bold m-0">$<%= number_with_precision(@transactions.sum(:amount), :precision => 2) %></p>
  <%# </div> %>

  <%= render @transactions %>
</div>

<%= link_to new_transaction_path, class: "link-btn btn
                  btn-success w-100 p-4 rounded-0" do %>
  <span class="p-3 border border-light">NEW PROJECTS</span>
<% end %>

app/views/transactions/new.html.erb
<% provide(:title, 'New Projects') %>

<%= form_for @transaction, html: { class: "mt-5 mx-3" } do |f| %>

  <%= f.text_field :name, class: "form-control", placeholder: "Name" %>

  <%= f.text_area :description, class: "form-control my-3", placeholder: "Description" %>

  <%# <div class="input-group">
    <div class="input-group-prepend">
      <div class="input-group-text">$</div>
    </div>
    <%= f.number_field :amount, class: "form-control", placeholder: "Amount", min: "0", step: "0.01" %>
  <%# </div> %>

  <%= collection_select(:transaction, :group_id, Group.all, :id, :name, { :prompt => 'Group' }, class: "form-control my-3" ) %>
 
  <%= f.submit class: "btn btn-primary my-4 mx-auto d-block" %>
  

  <%= render  partial: 'shared/form_errors', locals: { model: @transaction } %>

<% end %>

app/views/transactions/no_grp.html.erb
<% provide(:title, 'No Group Projects') %>

<div>
  <%# <div class="card mb-3 p-3 flex-row justify-content-between border-top-0" id="trn-total">
    <h5 class="text-muted m-0">Total Amount</h5>
    <p class="font-weight-bold m-0">$<%= number_with_precision(@transactions.sum(:amount), :precision => 2) %></p>
  <%# </div> %>

  <%= render @transactions %>
</div>

<%= link_to new_transaction_path, class: "link-btn btn
                    btn-success w-100 p-4 rounded-0" do %>
  <span class="p-3 border border-light">NEW PROJECTS</span>
<% end %>

app/views/transactions/show.html.erb
<% provide(:title, 'Details') %>

<ul class="card mx-3 list-group list-group-flush p-3">
  <li class="list-group-item p-0">
    <div class="mt-2 mb-4 d-flex">
      <% if @transaction.group %>
        <img src="<%= @transaction.group.icon %>" alt="" class="border border-warning rounded">
      <% else %>
        <div class="img-frame border border-warning rounded my-auto ml-2">
          <small class="text-muted d-block text-center mt-5 font-weight-bold">no group</small>
        </div>
      <% end %>
      <h4 class="my-auto pl-3"><%= @transaction.name %></h4>
    </div>
    <p class="text-muted"><%= @transaction.description %></p>
  </li>

  <li class="list-group-item p-0 pt-3 d-flex justify-content-between">
    <p class="">Transaction no.<%= @transaction.id %></p>
    <p class=""><small class="text-muted"><%= @transaction.created_at.strftime('%d %b %Y at %l:%M%P') %></small></p>
  </li>

  <%# <li class="list-group-item d-flex justify-content-between p-0 pt-3">
    <p class="m-0">AMOUNT</p>
    <span class="font-weight-bold">$<%= number_with_precision(@transaction.amount, :precision => 2) %></span>
  <%# </li> %>
</ul>

<% flash.each do |m_type, msg| %>
  <div class="alert alert-<%= m_type %> w-75 mx-auto text-center mt-3">
    <%= msg %>
  </div>
<% end %>

<%= link_to new_transaction_path, class: "link-btn btn
                  btn-success w-100 p-4 rounded-0" do %>
  <span class="p-3 border border-light">NEW PROJECTS</span>
<% end %>

app/views/users/login.html.erb
<% provide(:title, 'Login') %>

<div class="d-flex flex-column h-75 justify-content-between mt-5 mx-3">
  <%= form_with scope: :session, url: login_path, html: { class: "" } do |f| %>

    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>

    <%= f.submit 'Log in', class: "btn btn-primary my-4 mx-auto d-block" %>
  <% end %>
  <p class="">New user? <%= link_to  'Sign up now!', signup_path %></p>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>

<%= form_for @user, html: { class: "mt-5 mx-3" } do |f| %>

  <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  
  <%= f.submit class: "btn btn-primary my-4 mx-auto d-block" %>
  
  <%= render  partial: 'shared/form_errors', locals: { model: @user } %>
  
<% end %>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>

<div class="profile-container h-100">
  <div class="text-center mb-5">
    <img src="<%= current_user.icon %>" alt="" class="lg-img card-img-top mt-5 border border-secondary rounded rounded-circle">
    <h4 class="card-title"><%= current_user.name %></h4>
  </div>

  <ul class="">
    <li class="list-group-item"><%= link_to 'All my projects', transactions_path %></li>
    <li class="list-group-item"><%= link_to 'All my external projects', transactions_no_grp_path %></li>
    <li class="list-group-item"><%= link_to 'All groups', groups_path %></li>
    <li class="list-group-item"><%= link_to  "Logout", logout_url, method: :delete %></li>
  </ul>

  <% flash.each do |m_type, msg| %>
    <div class="alert alert-<%= m_type %> w-75 mx-auto text-center mt-3">
      <%= msg %>
    </div>
  <% end %>
</div>